# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo',
            name='esAutomotora',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipo',
            name='esParticular',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
