# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 04:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170616_0345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automotora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreAutomotora', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('comuna', models.CharField(max_length=200)),
                ('telefono', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Carroceria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCarroceria', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCiudad', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreContacto', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('comuna', models.CharField(max_length=200)),
                ('telefono', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('automotora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Automotora')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Ciudad')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='ContactoVehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Edicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechadePublicacion', models.DateTimeField()),
                ('valorAnterior', models.CharField(max_length=200)),
                ('valorNuevo', models.CharField(max_length=200)),
                ('campoEditado', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMarca', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreModelo', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=10)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePais', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Particular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreParticular', models.CharField(max_length=100)),
                ('personalIdentifier', models.IntegerField()),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Ciudad')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreRegion', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('sigla', models.CharField(max_length=10)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Pais')),
            ],
        ),
        migrations.CreateModel(
            name='TipoCambio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTipoCambio', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilometraje', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('anno', models.IntegerField()),
                ('puertas', models.IntegerField()),
                ('cilindrada', models.IntegerField()),
                ('colorExterior', models.CharField(max_length=100)),
                ('combustible', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('esNuevo', models.BooleanField()),
                ('aireAcondicionado', models.BooleanField()),
                ('alzavidriosElectricos', models.BooleanField()),
                ('espejosElectricos', models.BooleanField()),
                ('frenosAbs', models.BooleanField()),
                ('airbag', models.BooleanField()),
                ('unicoDuenno', models.BooleanField()),
                ('cierreCentralizado', models.BooleanField()),
                ('convertidorCatalitico', models.BooleanField()),
                ('llantas', models.BooleanField()),
                ('radio', models.BooleanField()),
                ('vendido', models.BooleanField()),
                ('fechadePublicacion', models.DateTimeField(auto_now=True)),
                ('carroceria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Carroceria')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Categoria')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Ciudad')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Marca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Modelo')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Tipo')),
                ('transmision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Transmision')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreVersion', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=250)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Modelo')),
            ],
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Version'),
        ),
        migrations.AddField(
            model_name='marca',
            name='paisDeOrigen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Pais'),
        ),
        migrations.AddField(
            model_name='edicion',
            name='tipoCambio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TipoCambio'),
        ),
        migrations.AddField(
            model_name='edicion',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Vehiculo'),
        ),
        migrations.AddField(
            model_name='contactovehiculo',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Vehiculo'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Region'),
        ),
        migrations.AddField(
            model_name='automotora',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Ciudad'),
        ),
        migrations.AddField(
            model_name='automotora',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Tipo'),
        ),
    ]
